### ISSUE TITLE
Please support FreeBSD

### ISSUE THREAD

**Issue by yurivict** [lambdalisue/rs-metrics-process#36]
There's no freebsd.rs

The Reth project can't be compiled on FreeBSD because of this problem.
https://github.com/paradigmxyz/reth/issues/5918

**Comment by mattsse** [comment]
I know little to nothing about freebsd or how to get the metrics values on that OS:

https://github.com/lambdalisue/rs-metrics-process/blob/dbb1d752e0b497d32853a6c7b3acd77d6f64157d/src/collector/linux.rs#L10

maybe via https://github.com/johalun/sysctl-rs and/or https://github.com/fubarnetes/rctl

but perhaps there can be `collect` that returns an empty Metrics for freebsd so that it at least compiles on freebsd?

**Comment by lambdalisue** [comment]
I've no idea about FreeBSD so I cannot implement it by myself. PR is welcome.

> but perhaps there can be collect that returns an empty Metrics for freebsd so that it at least compiles on freebsd?

Not sure if that should be applied on this crate. I think user (in this case, reth?) should remove this crate with `#cfg()` instead.

**Comment by lambdalisue** [comment]
Maybe we can add `dummy` feature that add a dummy collector that is used for non supported platform?

**Comment by mattsse** [comment]
that would be very useful imo, just so that it compiles

**Comment by lambdalisue** [comment]
A `dummy` feature is added. Please close the issue if that is what you needed actually or keep open it if you really need FreeBSD support @yurivict

**Comment by lambdalisue** [comment]
#53
